import React from 'react';
import "./Academics.css";
const Academics = () => {
  return (
    <div className="academics">
      <h2>Academics</h2>
      <section>
        <h3>Primary Education</h3>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tenetur eligendi asperiores numquam molestiae, perferendis soluta maxime provident laboriosam hic placeat harum enim rem vitae esse atque tempore incidunt dolorum. Corrupti quod vel aut iste voluptatum temporibus totam eum animi illum quibusdam quidem tempore vitae esse sunt dicta, cupiditate eius dolorem! Alias maxime, mollitia vel, quia obcaecati dolorum iure hic sequi quam expedita incidunt, labore ipsum. Nostrum fugiat distinctio, odit repellendus illum sint, reiciendis nesciunt explicabo repellat neque possimus perspiciatis earum expedita quasi vitae tempora tenetur eaque optio quas perferendis facilis! Perspiciatis enim illo quibusdam! Quibusdam, delectus voluptates! Autem, facere enim libero ea consectetur a dolorem in obcaecati alias amet dolor accusamus veritatis, reprehenderit, voluptatibus rem totam animi earum? Repellat qui dolorum recusandae id asperiores explicabo, minima saepe atque illo, dolores obcaecati ratione iure tenetur hic alias consequatur a? Dolor magni tempora incidunt unde ipsum eius iure sed ducimus! Repellendus ad minus laboriosam, distinctio rerum exercitationem nostrum debitis quaerat enim sequi saepe eaque at quo quidem voluptatum eveniet et? Nihil voluptatum labore quos amet tenetur rerum nemo recusandae accusamus ab alias officia iste nesciunt rem, excepturi fugiat suscipit quas doloribus. Sint placeat amet ea pariatur quidem fugiat magni sunt enim voluptatem.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tenetur eligendi asperiores numquam molestiae, perferendis soluta maxime provident laboriosam hic placeat harum enim rem vitae esse atque tempore incidunt dolorum. Corrupti quod vel aut iste voluptatum temporibus totam eum animi illum quibusdam quidem tempore vitae esse sunt dicta, cupiditate eius dolorem! Alias maxime, mollitia vel, quia obcaecati dolorum iure hic sequi quam expedita incidunt, labore ipsum. Nostrum fugiat distinctio, odit repellendus illum sint, reiciendis nesciunt explicabo repellat neque possimus perspiciatis earum expedita quasi vitae tempora tenetur eaque optio quas perferendis facilis! Perspiciatis enim illo quibusdam! Quibusdam, delectus voluptates! Autem, facere enim libero ea consectetur a dolorem in obcaecati alias amet dolor accusamus veritatis, reprehenderit, voluptatibus rem totam animi earum? Repellat qui dolorum recusandae id asperiores explicabo, minima saepe atque illo, dolores obcaecati ratione iure tenetur hic alias consequatur a? Dolor magni tempora incidunt unde ipsum eius iure sed ducimus! Repellendus ad minus laboriosam, distinctio rerum exercitationem nostrum debitis quaerat enim sequi saepe eaque at quo quidem voluptatum eveniet et? Nihil voluptatum labore quos amet tenetur rerum nemo recusandae accusamus ab alias officia iste nesciunt rem, excepturi fugiat suscipit quas doloribus. Sint placeat amet ea pariatur quidem fugiat magni sunt enim voluptatem.</p>
      </section>
      <br /><br /><hr />
      <section>
        <h3>Secondary Education</h3>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tenetur eligendi asperiores numquam molestiae, perferendis soluta maxime provident laboriosam hic placeat harum enim rem vitae esse atque tempore incidunt dolorum. Corrupti quod vel aut iste voluptatum temporibus totam eum animi illum quibusdam quidem tempore vitae esse sunt dicta, cupiditate eius dolorem! Alias maxime, mollitia vel, quia obcaecati dolorum iure hic sequi quam expedita incidunt, labore ipsum. Nostrum fugiat distinctio, odit repellendus illum sint, reiciendis nesciunt explicabo repellat neque possimus perspiciatis earum expedita quasi vitae tempora tenetur eaque optio quas perferendis facilis! Perspiciatis enim illo quibusdam! Quibusdam, delectus voluptates! Autem, facere enim libero ea consectetur a dolorem in obcaecati alias amet dolor accusamus veritatis, reprehenderit, voluptatibus rem totam animi earum? Repellat qui dolorum recusandae id asperiores explicabo, minima saepe atque illo, dolores obcaecati ratione iure tenetur hic alias consequatur a? Dolor magni tempora incidunt unde ipsum eius iure sed ducimus! Repellendus ad minus laboriosam, distinctio rerum exercitationem nostrum debitis quaerat enim sequi saepe eaque at quo quidem voluptatum eveniet et? Nihil voluptatum labore quos amet tenetur rerum nemo recusandae accusamus ab alias officia iste nesciunt rem, excepturi fugiat suscipit quas doloribus. Sint placeat amet ea pariatur quidem fugiat magni sunt enim voluptatem.</p>
      </section>
      <br /><br /><hr />
      <section>
        <h3>Senior Secondary Education</h3>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tenetur eligendi asperiores numquam molestiae, perferendis soluta maxime provident laboriosam hic placeat harum enim rem vitae esse atque tempore incidunt dolorum. Corrupti quod vel aut iste voluptatum temporibus totam eum animi illum quibusdam quidem tempore vitae esse sunt dicta, cupiditate eius dolorem! Alias maxime, mollitia vel, quia obcaecati dolorum iure hic sequi quam expedita incidunt, labore ipsum. Nostrum fugiat distinctio, odit repellendus illum sint, reiciendis nesciunt explicabo repellat neque possimus perspiciatis earum expedita quasi vitae tempora tenetur eaque optio quas perferendis facilis! Perspiciatis enim illo quibusdam! Quibusdam, delectus voluptates! Autem, facere enim libero ea consectetur a dolorem in obcaecati alias amet dolor accusamus veritatis, reprehenderit, voluptatibus rem totam animi earum? Repellat qui dolorum recusandae id asperiores explicabo, minima saepe atque illo, dolores obcaecati ratione iure tenetur hic alias consequatur a? Dolor magni tempora incidunt unde ipsum eius iure sed ducimus! Repellendus ad minus laboriosam, distinctio rerum exercitationem nostrum debitis quaerat enim sequi saepe eaque at quo quidem voluptatum eveniet et? Nihil voluptatum labore quos amet tenetur rerum nemo recusandae accusamus ab alias officia iste nesciunt rem, excepturi fugiat suscipit quas doloribus. Sint placeat amet ea pariatur quidem fugiat magni sunt enim voluptatem.</p>
      </section>
    </div>
  );
};

export default Academics;
